############  Segmentation Models  ############
yolov8-seg:
  description: "YOLOv8 Segmentation Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      conf_port: 1
      conf_shape: [80, 80, 80]
      mask_coef_port: 3
      mask_coef_shape: [32, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 4
      coord_shape: [64, 40, 40]
      conf_port: 5
      conf_shape: [80, 40, 40]
      mask_coef_port: 6
      mask_coef_shape: [32, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 7
      coord_shape: [64, 20, 20]
      conf_port: 8
      conf_shape: [80, 20, 20]
      mask_coef_port: 9
      mask_coef_shape: [32, 20, 20]
    mask_proto_port: 2
    mask_proto_shape: [32, 160, 160]
  port_order: [coord, conf, mask_proto, mask_coef, coord, conf, mask_coef, coord, conf, mask_coef]

yolo11-seg:
  description: "YOLO11 Segmentation Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      mask_coef_port: 2
      mask_coef_shape: [32, 80, 80]
      conf_port: 3
      conf_shape: [80, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 4
      coord_shape: [64, 40, 40]
      mask_coef_port: 5
      mask_coef_shape: [32, 40, 40]
      conf_port: 6
      conf_shape: [80, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 7
      coord_shape: [64, 20, 20]
      mask_coef_port: 8
      mask_coef_shape: [32, 20, 20]
      conf_port: 9
      conf_shape: [80, 20, 20]
    mask_proto_port: 1
    mask_proto_shape: [32, 160, 160]
  port_order: [coord, mask_proto, mask_coef, conf, coord, mask_coef, conf, coord, mask_coef, conf]

############  Pose Models  ############
yolo8-pose:
  description: "YOLO8 Pose Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      conf_port: 1
      conf_shape: [1, 80, 80]
      keypt_port: 2
      keypt_shape: [51, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 3
      coord_shape: [64, 40, 40]
      conf_port: 4
      conf_shape: [1, 40, 40]
      keypt_port: 5
      keypt_shape: [51, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 6
      coord_shape: [64, 20, 20]
      conf_port: 7
      conf_shape: [1, 20, 20]
      keypt_port: 8
      keypt_shape: [51, 20, 20]
  port_order: [coord, conf, keypt, coord, conf, keypt, coord, conf, keypt]

yolo11-pose:
  description: "YOLO11 Pose Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      conf_port: 2
      conf_shape: [1, 80, 80]
      keypt_port: 1
      keypt_shape: [51, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 3
      coord_shape: [64, 40, 40]
      conf_port: 5
      conf_shape: [1, 40, 40]
      keypt_port: 4
      keypt_shape: [51, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 6
      coord_shape: [64, 20, 20]
      conf_port: 8
      conf_shape: [1, 20, 20]
      keypt_port: 7
      keypt_shape: [51, 20, 20]
  port_order: [coord, keypt, conf, coord, keypt, conf, coord, keypt, conf]

############  Detection Models  ############
yolov8-det:
    description: "YOLOv8 Detection Model Port Configuration"
    layers:
      layer_0:  # 80x80 grid, stride 8
        coord_port: 0
        coord_shape: [64, 80, 80]
        conf_port: 1
        conf_shape: [80, 80, 80]
      layer_1:  # 40x40 grid, stride 16
        coord_port: 2
        coord_shape: [64, 40, 40]
        conf_port: 3
        conf_shape: [80, 40, 40]
      layer_2:  # 20x20 grid, stride 32
        coord_port: 4
        coord_shape: [64, 20, 20]
        conf_port: 5
        conf_shape: [80, 20, 20]
    port_order: [coord, conf, coord, conf, coord, conf]

yolov9-det:
  description: "YOLOv9 Detection Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      conf_port: 1
      conf_shape: [80, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 2
      coord_shape: [64, 40, 40]
      conf_port: 3
      conf_shape: [80, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 4
      coord_shape: [64, 20, 20]
      conf_port: 5
      conf_shape: [80, 20, 20]
  port_order: [coord, conf, coord, conf, coord, conf]

yolo11-det:
  description: "YOLO11 Detection Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      conf_port: 1
      conf_shape: [80, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 2
      coord_shape: [64, 40, 40]
      conf_port: 3
      conf_shape: [80, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 4
      coord_shape: [64, 20, 20]
      conf_port: 5
      conf_shape: [80, 20, 20]
  port_order: [coord, conf, coord, conf, coord, conf]

yolo10-det:
  description: "YOLO10 Detection Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [64, 80, 80]
      conf_port: 1
      conf_shape: [80, 80, 80]
    layer_1:  # 40x40 grid, stride 16
      coord_port: 2
      coord_shape: [64, 40, 40]
      conf_port: 3
      conf_shape: [80, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 4
      coord_shape: [64, 20, 20]
      conf_port: 5
      conf_shape: [80, 20, 20]
  port_order: [coord, conf, coord, conf, coord, conf]

yolo7-det:
  description: "YOLOv7 Detection Model Port Configuration"
  layers:
    layer_0:  # 80x80 grid, stride 8
      coord_port: 0
      coord_shape: [255, 80, 80]  
      conf_port: 0
      conf_shape: [255, 80, 80]   
    layer_1:  # 40x40 grid, stride 16
      coord_port: 1
      coord_shape: [255, 40, 40]
      conf_port: 1
      conf_shape: [255, 40, 40]
    layer_2:  # 20x20 grid, stride 32
      coord_port: 2
      coord_shape: [255, 20, 20]
      conf_port: 2
      conf_shape: [255, 20, 20]
  port_order: [coord, conf, coord, conf, coord, conf]  